name: "💉 Failing Test"
description: Report failing tests or CI jobs
title: "[TEST] "
labels: ["Type: Test"]
assignees:
  - JakobLierman
body:
  - type: textarea
    id: tests
    attributes:
      label: Which jobs/test(s) are failing?
      description: The CI jobs or tests that are failing.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for failure/description
      description: Try to describe why the test is failing or what we are missing to make it pass.
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media prove
      description: If applicable, add screenshots or videos to help explain your problem.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
