name: "📚 Documentation Issue Report"
description: "Report an issue in the project's documentation or README.md file."
title: "[Docs]: "
labels: ["Documentation"]
assignees:
  - JakobLierman
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: Write down the steps to reproduce the error
      placeholder: |
        1. Use x argument / navigate to
        2. Fill this information
        3. Go to...
        4. See error
      value: |
        1.
  - type: textarea
    id: expected
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
