name: "🚀➕ Enhancement Request"
description: "Suggest an enhancement for this project. Improve an existing feature."
labels: ["Type: Enhancement"]
assignees: 
  - JakobLierman
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your enhancement request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
