name: "⚠️ Security Report"
description: "Report an issue to help the project improve."
labels: ["Type: Security"]
assignees: 
  - JakobLierman
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the security issue
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: Write down the steps to reproduce the error
      placeholder: |
        1. Use x argument / navigate to
        2. Fill this information
        3. Go to...
        4. See error
      value: |
        1.
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: media
    attributes:
      label: Media prove
      description: If applicable, add screenshots or videos to help explain your problem.
  - type: textarea
    id: environment
    attributes:
      label: Your environment
      description: Use all the applicable bulleted list elements for this specific issue, and remove all the bulleted list elements that are not relevant for this issue.
      placeholder: |
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
        - **Browser name and version**: Chromium version 120.0.6099.234
      value: |
        - OS:
        - Node:
        - npm:
        - Browser name and version:
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or additional information about the problem here.
