name: "❓ Question or Support Request"
description: "Questions and requests for support."
labels: ["Type: Question"]
assignees: 
  - JakobLierman
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your question or ask for support.
      description: A clear and concise description of what your doubt is.
    validations:
      required: true
