name: Update copyright year(s) in license file

on:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 AM on January 1

permissions:
  contents: write
  pull-requests: write

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update License Year
        uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: LICENSE
          branchName: license/copyright-to-{{currentYear}}
          commitTitle: "docs(license): update copyright year(s)"
          commitBody: Let's keep legal happy.
          commitAuthorName: "${GITHUB_ACTOR}"
          commitAuthorEmail: "${GITHUB_ACTOR}@users.noreply.github.com"
          gpgPrivateKey: ${{ secrets.gpgPrivateKey }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
          prTitle: "docs(license): update copyright year(s)"
          prBody: It's that time of the year, let's update the license.
          assignees: JakobLierman
          labels: "Documentation"
      - name: Merge PR
        if: steps.license.outputs.pullRequestNumber != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Replace '--merge' with '--rebase' to rebase the commits onto the base
        # branch, or with '--squash' to squash the commits into one commit and
        # merge it into the base branch.
        # For more information regarding the merge command, please see
        # https://cli.github.com/manual/gh_pr_merge.
        run: gh pr merge --merge --delete-branch ${{ steps.license.outputs.pullRequestNumber }}
